# Generated by Django 3.2.16 on 2024-04-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240422_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='loсation',
            new_name='location',
        ),
    ]
